default: &default
  adapter: postgresql
  encoding: unicode
  database: my_db
  pool: 5
  username: postgres
  password: docker
  host: 172.24.4.7
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: my_db
  pool: 5
  username: postgres
  password: docker
  host: 172.24.4.7
  port: 5432
