default: &default
  adapter: postgresql
  encoding: unicode
  database: my_db
  pool: 5
  username: postgres
  password: docker
  host: 10.20.32.25
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: my_db
  pool: 5
  username: postgres
  password: docker
  host: 10.20.32.25
  port: 5432
